name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Cambia "main" por la rama que deseas utilizar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run deploy  # Cambia "build" por el script de compilación de tu proyecto

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/  # Cambia "./build" por el directorio de compilación de tu proyecto